### ISSUE TITLE
Error with pip 10

### ISSUE THREAD

**Issue by jsga** [GlobalStudioES/pymongodm#1]
Hey!

Im getting this error when installing the package:

```
 $ pip install pymongodm
 Collecting pymongodm
  Using cached https://files.pythonhosted.org/packages/ce/7e/83c03aaa3de69d189394d188c131f03fdf05edc31ff8e9121eaea66c1e5a/pymongodm-2.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>

      File "/tmp/pip-install-5te2wbzz/pymongodm/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5te2wbzz/pymongodm/
```
Just for your info:
```
$ pip --version
pip 10.0.1
$ python3 --version
Python 3.6.5 :: Anaconda custom (64-bit)
```

Check out this issue, might be the same problem: [https://stackoverflow.com/questions/25192794/no-module-named-pip-req/49867265#49867265](https://stackoverflow.com/questions/25192794/no-module-named-pip-req/49867265#49867265)

**Comment by agalera** [comment]
@jsga I just updated the lib in pip, it seems to work for me, can you try?

**Comment by jsga** [comment]
Thanks @agalera ! Now Im getting a different error

```
$ pip install pymongodm==2.0.5
Collecting pymongodm==2.0.5
  Using cached https://files.pythonhosted.org/packages/0c/bb/4e3115db1f92a79473e6d6122a5d51ff1e764fff682c102e7d44c668cbf4/pymongodm-2.0.5.tar.gz
Collecting pymongo==3.2.2 (from pymongodm==2.0.5)
  Using cached https://files.pythonhosted.org/packages/5a/59/d4faf11957b03a470882670f5f7dafd424a0364fdc0d8c7e8ab53f58ac40/pymongo-3.2.2.tar.gz
Collecting pypandoc==1.1.3 (from pymongodm==2.0.5)
  Using cached https://files.pythonhosted.org/packages/41/68/e985491370cc44a063ac5c70232bf72d7675fa7539a86fa7fa08257bda05/pypandoc-1.1.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7j5rhv9e/pypandoc/setup.py", line 20, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/tmp/pip-install-7j5rhv9e/pypandoc/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/tmp/pip-install-7j5rhv9e/pypandoc/pypandoc/__init__.py", line 70, in _convert
        from_formats, to_formats = get_pandoc_formats()
      File "/tmp/pip-install-7j5rhv9e/pypandoc/pypandoc/__init__.py", line 207, in get_pandoc_formats
        str(comm))
    RuntimeError: Couldn't call pandoc to get output formats. Output from pandoc:
    (b'pandoc [OPTIONS] [FILES]\n  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT                    \n  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT                     \n  -o FILENAME           --output=FILENAME                               \n                        --data-dir=DIRECTORY                            \n  -R                    --parse-raw                                     \n  -S                    --smart                                         \n                        --old-dashes                                    \n                        --base-header-level=NUMBER                      \n                        --indented-code-classes=STRING                  \n  -F PROGRAM            --filter=PROGRAM                                \n                        --normalize                                     \n  -p                    --preserve-tabs                                 \n                        --tab-stop=NUMBER                               \n                        --track-changes=accept|reject|all               \n                        --file-scope                                    \n                        --extract-media=PATH                            \n  -s                    --standalone                                    \n                        --template=FILENAME                             \n  -M KEY[:VALUE]        --metadata=KEY[:VALUE]                          \n  -V KEY[:VALUE]        --variable=KEY[:VALUE]                          \n  -D FORMAT             --print-default-template=FORMAT                 \n                        --print-default-data-file=FILE                  \n                        --dpi=NUMBER                                    \n                        --no-wrap                                       \n                        --wrap=auto|none|preserve                       \n                        --columns=NUMBER                                \n                        --toc, --table-of-contents                      \n                        --toc-depth=NUMBER                              \n                        --no-highlight                                  \n                        --highlight-style=STYLE                         \n  -H FILENAME           --include-in-header=FILENAME                    \n  -B FILENAME           --include-before-body=FILENAME                  \n  -A FILENAME           --include-after-body=FILENAME                   \n                        --self-contained                                \n                        --html-q-tags                                   \n                        --ascii                                         \n                        --reference-links                               \n                        --reference-location=block|section|document     \n                        --atx-headers                                   \n                        --chapters                                      \n                        --top-level-division=section|chapter|part       \n  -N                    --number-sections                               \n                        --number-offset=NUMBERS                         \n                        --no-tex-ligatures                              \n                        --listings                                      \n  -i                    --incremental                                   \n                        --slide-level=NUMBER                            \n                        --section-divs                                  \n                        --default-image-extension=extension             \n                        --email-obfuscation=none|javascript|references  \n                        --id-prefix=STRING                              \n  -T STRING             --title-prefix=STRING                           \n  -c URL                --css=URL                                       \n                        --reference-odt=FILENAME                        \n                        --reference-docx=FILENAME                       \n                        --epub-stylesheet=FILENAME                      \n                        --epub-cover-image=FILENAME                     \n                        --epub-metadata=FILENAME                        \n                        --epub-embed-font=FILE                          \n                        --epub-chapter-level=NUMBER                     \n                        --latex-engine=PROGRAM                          \n                        --latex-engine-opt=STRING                       \n                        --bibliography=FILE                             \n                        --csl=FILE                                      \n                        --citation-abbreviations=FILE                   \n                        --natbib                                        \n                        --biblatex                                      \n  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]        \n                        --mathml[=URL]                                  \n                        --mimetex[=URL]                                 \n                        --webtex[=URL]                                  \n                        --jsmath[=URL]                                  \n                        --mathjax[=URL]                                 \n                        --katex[=URL]                                   \n                        --katex-stylesheet=URL                          \n                        --gladtex                                       \n                        --trace                                         \n                        --dump-args                                     \n                        --ignore-args                                   \n                        --verbose                                       \n                        --bash-completion                               \n                        --list-input-formats                            \n                        --list-output-formats                           \n                        --list-extensions                               \n                        --list-highlight-languages                      \n                        --list-highlight-styles                         \n  -v                    --version                                       \n  -h                    --help                                          \n', None)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7j5rhv9e/pypandoc/
```

**Comment by agalera** [comment]
@jsga I have eliminated dependency with pypandoc, now it should work

It is not necessary for the user to have it, since it is only used to generate the pypi package correctly

**Comment by jsga** [comment]
Fixed! :)
